export const runtime = "nodejs";
export const dynamic = "force-dynamic";

import { NextResponse } from "next/server";
import { sendMail } from "@/lib/mailer";
import { tplLocalAirtel, tplSwift } from "@/lib/email-templates";

/**
 * POST body:
 * {
 *   type: "local" | "swift",
 *   to: "donor@example.com",
 *   donorName?: string,
 *   amount: number,
 *   currency: string,
 *   reference: string,
 *   // local:
 *   merchantCode?: string,
 *   // swift:
 *   swiftPdf?: Buffer (optional if you want to attach)
 * }
 */
export async function POST(req: Request) {
  try {
    const body = await req.json();
    const { type, to, donorName, amount, currency, reference } = body;

    if (!type || !to || !amount || !currency || !reference) {
      return NextResponse.json({ ok: false, error: "Missing fields" }, { status: 400 });
    }

    if (type === "local") {
      const merchantCode = body.merchantCode || "6890724";
      await sendMail({
        to,
        subject: `Your Airtel Merchant Instructions – Ref ${reference}`,
        html: tplLocalAirtel({ donorName, amount, currency, reference, merchantCode }),
      });
      return NextResponse.json({ ok: true });
    }

    // type === "swift"
    // Optional: attach SWIFT PDF generated by your route (or let the initiate route send a separate email with attachment)
    const attachments = body.swiftPdf
      ? [{ filename: `HumbleVessel_SWIFT_${reference}.pdf`, content: Buffer.from(body.swiftPdf.data) }]
      : undefined;

    await sendMail({
      to,
      subject: `Your SWIFT Instructions – Ref ${reference}`,
      html: tplSwift({ donorName, amount, currency, reference }),
      attachments,
    });

    return NextResponse.json({ ok: true });
  } catch (e: any) {
    return NextResponse.json({ ok: false, error: e.message }, { status: 500 });
  }
}
